# These are supported funding model platforms

github: [syntaxspins,trindadedev13,RohitKushvaha01,itsvks19,yamenher] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
# Replace with a single Patreon username
# Replace with a single Open Collective username
 # Replace with a single Ko-fi username
# Replace with a single Tidelift platform-name/package-name e.g., npm/babel # Replace with a single Community Bridge project-name e.g., cloud-foundry
 # Replace with a single Liberapay username
 # Replace with a single IssueHunt username
 # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
 # Replace with a single Polar username
 # Replace with a single Buy Me a Coffee username
 # Replace with a single thanks.dev username
# Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
