name: Commitlint

on:
  push:
    branches:
      - main
      - workflowname: Commitlint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
      - name: Lint commits
        uses: wagoid/commitlint-github-action@v5

  pull_request:
    branches:
      - main
      - workflow

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

     
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Run Commitlint
  
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose
          else
            npx commitlint --from ${{ github.event.before }} --to ${{ github.event.after }} --verbose
          fi